#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Silex\Application;
use Saxulum\Console\Provider\ConsoleProvider;

$app = new Application([
    'debug' => true
]);

$app->register(new ConsoleProvider());

require __DIR__ . '/app/providers.php';

require __DIR__ . '/app/controllers.php';

require __DIR__ . '/app/routing.php';

$app['console']->run();
